### PR TITLE
added computation of noise strength kernel

### PR DESCRIPTION
**Pull request by evcano**
Hi @danielpeter,

I added some subroutines to compute and save the noise strength kernel as done in the SPECFEM3D_CARTESIAN and GLOBAL versions.

Feel free to modify at your convenience,
Best wishes.

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed require a buildbot test. Buildbot has started.

**Comment by buildbot-princeton** [comment]
Your changes passed the buildbot test. See [build 793](http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/793).

**Comment by danielpeter** [comment]
great, looks good. that was quick!

**Comment by danielpeter** [comment]
accept

On 10 Mar 2023, at 1:45 PM, buildbot-princeton ***@***.******@***.***>> wrote:



Your changes passed the buildbot test. See build 793<https://urldefense.com/v3/__http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/793__;!!Nmw4Hv0!0wjuws8maVskfizELx2GX3gTYPAh2BT0U6vlLzFgOHJc_U5-lc58wYyjrT8XuOgK7zJZgfJSbn7JgbAaEwJ9s6hBMhsT6PY$>.

**Pull request merged**
